**Author - Vihara thejaka Kularathna**

peer reviwer - Muhammad Abdullah

Clear Structure

Adequate Commenting

No Errors

# import required Libraries

In [1]:
#importing the pandas library for data manipulation and analysis
import pandas as pd
#importing ploty express for interactive data visualisation
import plotly.express as px
#importing sklearn preprocessing tools for encoding
from sklearn import preprocessing

# loading the dataset
**Seminar 1 page 9**

Load the raw loan application dataset from google collab into a pandas data frame named data_frame using the pd.csv()

In [2]:
#loading the  dataset into the data frame
data_frame = pd.read_csv('/content/loan_applications_data.csv')

/tmp/ipykernel_64532/3122193930.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  data_frame = pd.read_csv('/content/loan_applications_data.csv')

# Acess the first 5 rows
**Seminar 1 page 9**

 Displaying the first 5 rows of the dataset with use of head() funtion

In [3]:
#displaying the  first 5 rows of the dataset
data_frame.head()

,id,applicant_account_No.,bank_sort_code,age,sex,education_qualifications,income,home_ownership,employment_length,loan_intent,loan_amount,loan_interest_rate,loan_income_ratio,payment_default_on_file,credit_history_length,loan_approval_status,max_loan_amount(allowed),credit_application_acceptance
0,717474,62012825,90025,21.0,M,Unknown,12000.0,OWN,0.0,EDUCATION,15000,6.99,0.12,N,4,Approved,-2426900,0.0
1,211588,3829308,239285,21.0,M,Unknown,13200.0,OWN,2.0,EDUCATION,25000,16.77,0.19,Y,3,Approved,-111739,0.0
2,597607,79622422,300083,23.0,M,Unknown,9600.0,RENT,5.0,MEDICAL,30000,12.42,0.31,N,3,Approved,-89000,0.0
3,684154,86043250,405179,40.0,M,Unknown,182004.0,RENT,3.0,EDUCATION,35000,8.00,0.19,N,11,Approved,35000,0.0
4,343369,73510088,300066,40.0,M,Unknown,90000.0,MORTGAGE,3.0,HOMEIMPROVEMENT,35000,12.42,0.39,N,14,Approved,35000,0.0

**Seminar 1 page 14**

For inpecting the data types using info() for printing out a summary of the dataframe which include each column data type and non null count. this helpful for identifying the formating issues

In [4]:
#this shows the variable data types
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58645 entries, 0 to 58644
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id                             58645 non-null  int64
 1   applicant_account_No.          58645 non-null  int64
 2   bank_sort_code                 58645 non-null  int64
 3   age                            58639 non-null  float64
 4   sex                            362 non-null    object
 5   education_qualifications       58645 non-null  object
 6   income                         58614 non-null  float64
 7   home_ownership                 58645 non-null  object
 8   employment_length              58630 non-null  float64
 9   loan_intent                    58645 non-null  object
 10  loan_amount                    58645 non-null  int64
 11  loan_interest_rate             58635 non-null  float64
 12  loan_income_ratio              58645 non-null  float64
 13  payment_default_on_file        58640 non-null  object
 14  credit_history_length          58645 non-null  int64
 15  loan_approval_status           58644 non-null  object
 16  max_loan_amount(allowed)       58645 non-null  int64
 17  credit_application_acceptance  58644 non-null  float64
dtypes: float64(6), int64(6), object(6)
memory usage: 8.1+ MB

# Display all column names
**seminar 1 page 14**

Printing all the coulmn names which are in the dataset. this is helpful for confirming the available features

In [5]:
#printing all the column names of the dataframe
list(data_frame.columns)

['id',
 'applicant_account_No.',
 'bank_sort_code',
 'age',
 'sex',
 'education_qualifications',
 'income',
 'home_ownership',
 'employment_length',
 'loan_intent',
 'loan_amount',
 'loan_interest_rate',
 'loan_income_ratio',
 'payment_default_on_file',
 'credit_history_length',
 'loan_approval_status',
 'max_loan_amount(allowed)',
 'credit_application_acceptance']

# Descriptive statistics - Numeric variables
**seminar 1 page 14**

Use to genarate the descrptive statistics for all the nueric variables which includes count, mean, max . this is need for identifying the value errors

In [6]:
# descriptive statistics for all numeric variables
data_frame.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
id,58645.0,5.494166e+05,2.600044e+05,100006.00,324881.00,548673.00,773531.00,9.999960e+05
applicant_account_No.,58645.0,5.055471e+07,2.864283e+07,1000384.00,25731092.00,50576780.00,75393934.00,9.999746e+07
bank_sort_code,58645.0,3.537375e+05,2.275277e+05,10004.00,165810.00,301495.00,600168.00,9.800000e+05
age,58639.0,2.755504e+01,6.099005e+00,-30.00,23.00,26.00,30.00,1.800000e+02
income,58614.0,6.405295e+04,3.793834e+04,4200.00,42000.00,58000.00,75662.00,1.900000e+06
employment_length,58630.0,4.702746e+00,3.999875e+00,0.00,2.00,4.00,7.00,1.500000e+02
loan_amount,58645.0,9.217557e+03,5.563807e+03,500.00,5000.00,8000.00,12000.00,3.500000e+04
loan_interest_rate,58635.0,1.068922e+01,3.257150e+00,-11.14,7.88,10.75,12.99,2.000000e+02
loan_income_ratio,58645.0,1.592375e-01,9.169179e-02,0.00,0.09,0.14,0.21,8.300000e-01
credit_history_length,58645.0,5.813062e+00,4.027495e+00,2.00,3.00,4.00,8.00,3.000000e+01
max_loan_amount(allowed),58645.0,2.823538e+05,5.148478e+07,-2426900.00,38003.00,62392.00,92716.00,1.246799e+10
credit_application_acceptance,58644.0,1.423846e-01,3.494471e-01,0.00,0.00,0.00,0.00,1.000000e+00

# Descriptive statistics - categorical variables
**seminar 1 page 14**

this prints a descriptive statistics for all the categorical variables which we can identify the inconsistent labels

In [7]:
# descriptive statistics for all categorical variables
data_frame.describe(include='object')

,sex,education_qualifications,home_ownership,loan_intent,payment_default_on_file,loan_approval_status
count,362,58645,58645,58645,58640,58644
unique,4,6,4,6,4,8
top,M,Unknown,RENT,EDUCATION,N,Approved
freq,126,58303,30594,12271,49933,50210

# Dataset dimensions
**seminar 1 page 15**

Uses Shape to printing the number of rows and columns in the dataset

In [8]:
#printing the number of rows and columns in the dataset
data_frame.shape

(58645, 18)

# finding missing values
**seminar 1 page 15**

isnull().sum and isna().sum() / len(data_frame) * 100 using for count and percentage of missing values per variable

In [9]:
#counting the number of missing values per column
data_frame.isnull().sum()

id                                   0
applicant_account_No.                0
bank_sort_code                       0
age                                  6
sex                              58283
education_qualifications             0
income                              31
home_ownership                       0
employment_length                   15
loan_intent                          0
loan_amount                          0
loan_interest_rate                  10
loan_income_ratio                    0
payment_default_on_file              5
credit_history_length                0
loan_approval_status                 1
max_loan_amount(allowed)             0
credit_application_acceptance        1
dtype: int64

**seminar 1 page 15**

In [10]:
# finding the percentage for the missing dasta values per variable
data_frame.isna().sum() / len(data_frame) * 100

id                                0.000000
applicant_account_No.             0.000000
bank_sort_code                    0.000000
age                               0.010231
sex                              99.382727
education_qualifications          0.000000
income                            0.052860
home_ownership                    0.000000
employment_length                 0.025578
loan_intent                       0.000000
loan_amount                       0.000000
loan_interest_rate                0.017052
loan_income_ratio                 0.000000
payment_default_on_file           0.008526
credit_history_length             0.000000
loan_approval_status              0.001705
max_loan_amount(allowed)          0.000000
credit_application_acceptance     0.001705
dtype: float64

# printing unique values for categorical variables
**seminar 1 page 18**

Using unique() for inspecting unique values in each categorical column for identifying inconsistent labels (trailing spaces, Mixed formats)

In [11]:
#printing unique values for the sex column
print("sex:", data_frame['sex'].unique())
#printing unique values in the education qualification column
print("education_qualifications:", data_frame['education_qualifications'].unique())
#printing unique values in the home ownership column
print("home_ownership:", data_frame['home_ownership'].unique())
#printing unique values in the loan intent column
print("loan_intent:", data_frame['loan_intent'].unique())
#printing unique values in the payment default on file column
print("payment_default_on_file:", data_frame['payment_default_on_file'].unique())
#printing unique value for the loan approval status column
print("loan_approval_status:", data_frame['loan_approval_status'].unique())

sex: ['M' 'F' nan 'Male' 'Female']
education_qualifications: ['Unknown ' 'Unknown' 'Higher Education' 'College' 'High School'
 'Apprenticeship ']
home_ownership: ['OWN' 'RENT' 'MORTGAGE' 'OTHER']
loan_intent: ['EDUCATION' 'MEDICAL' 'HOMEIMPROVEMENT' 'VENTURE' 'DEBTCONSOLIDATION'
 'PERSONAL']
payment_default_on_file: ['N' 'Y' nan 'NO' 'YES']
loan_approval_status: ['Approved' 'APPROVED' 'APPROVED ' 'Declined ' 'DECLINED ' 'Reject' nan
 'Accept' 'Accept ']

# Data visualisation
**seminar 2 page 2**

plotting out a interactive histogram  with the using of px.histogram() for visualizing frequency distribution of numeric variable

In [12]:
#visualising a histogram for frequency distribution of applicant age
age_fig = px.histogram(data_frame, x='age', title='Distribution of Applicant Age')
age_fig.show()

**Seminar 2 page 2**

In [13]:
#visualizing a histogram for frequency distrbution of applicant income
income_fig = px.histogram(data_frame, x='income', title='Distribution of Applicant Income')
income_fig.show()

**Seminar 2 page 2**

In [14]:
#visualizing a histogram for frquency distrbution of loan amount
loan_amount_fig = px.histogram(data_frame, x='loan_amount', title='Distribution of Loan Amount')
loan_amount_fig.show()

**Seminar 2 page 2**

In [15]:
#visualising a histogram for frequency distribution of loan intrest rate
interest_fig = px.histogram(data_frame, x='loan_interest_rate', title='Distribution of Loan Interest Rate')
interest_fig.show()

**Seminar 2 page 2**

plots interactive bar chart for loan intent using px.bar() for visualising the frquency distribution of the categorical variables

In [16]:
#visualizing a bar chart of he distribution of loan intent
intent_fig = px.bar(data_frame, x='loan_intent', title='Distribution of Loan Intent')
intent_fig.show()

# Scatter plots
**Seminar 2 page 3**


plotting an interactive scatter plot for visualizing income vs loan amount using px.scatter()

In [17]:
#visualizing a scatter plot for the showing the association between income and the loan amount
income_loan_fig = px.scatter(x=data_frame['income'], y=data_frame['loan_amount'],title='Income vs Loan Amount')
income_loan_fig.show()

#Box plot  

**Seminar 2 page 8**

plots interactive box plots for income,loan amount and the max loan amount using px.box() for identifying the outlier values visually

In [18]:
#visualizing a box plot for identifying the income
income_box_fig = px.box(data_frame, x='income', title='Box Plot of Applicant Income')
income_box_fig.show()

**Seminar 2 page 8**

In [19]:
#vislizing a box plot for identifying the loan amount
loan_box_fig = px.box(data_frame, x='loan_amount', title='Box Plot of Loan Amount')
loan_box_fig.show()

**Seminar 2 page 8**

In [20]:
#visualizing a box plot for finding max loan ammount
max_loan_box_fig = px.box(data_frame, x='max_loan_amount(allowed)',title='Box Plot of Maximum Loan Amount (Allowed)')
max_loan_box_fig.show()

# Data Preparation
**Seminar 2 page 7**

reloading the dataset into a new variable df using pd.read_csv() and displaying the transponse descrptive statistics for starting the data preparation phrase

In [21]:
#loading the prepared dataset
df = pd.read_csv('/content/loan_applications_data.csv', low_memory=False)
#using transpose for descriptive statistics for inspecting all numeric variable stat ata glace
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
id,58645.0,5.494166e+05,2.600044e+05,100006.00,324881.00,548673.00,773531.00,9.999960e+05
applicant_account_No.,58645.0,5.055471e+07,2.864283e+07,1000384.00,25731092.00,50576780.00,75393934.00,9.999746e+07
bank_sort_code,58645.0,3.537375e+05,2.275277e+05,10004.00,165810.00,301495.00,600168.00,9.800000e+05
age,58639.0,2.755504e+01,6.099005e+00,-30.00,23.00,26.00,30.00,1.800000e+02
income,58614.0,6.405295e+04,3.793834e+04,4200.00,42000.00,58000.00,75662.00,1.900000e+06
employment_length,58630.0,4.702746e+00,3.999875e+00,0.00,2.00,4.00,7.00,1.500000e+02
loan_amount,58645.0,9.217557e+03,5.563807e+03,500.00,5000.00,8000.00,12000.00,3.500000e+04
loan_interest_rate,58635.0,1.068922e+01,3.257150e+00,-11.14,7.88,10.75,12.99,2.000000e+02
loan_income_ratio,58645.0,1.592375e-01,9.169179e-02,0.00,0.09,0.14,0.21,8.300000e-01
credit_history_length,58645.0,5.813062e+00,4.027495e+00,2.00,3.00,4.00,8.00,3.000000e+01
max_loan_amount(allowed),58645.0,2.823538e+05,5.148478e+07,-2426900.00,38003.00,62392.00,92716.00,1.246799e+10
credit_application_acceptance,58644.0,1.423846e-01,3.494471e-01,0.00,0.00,0.00,0.00,1.000000e+00

# Remove unncessary variables

**Seminar 2 page 7**

Dropping unnnessary columns id, applicant account number, bank sort code, sex and the credit application acceptance. USing drop() because they are identifies as highly missing ,identifiers or cause lekage

In [22]:
#removing unncessary variables which are using as identifiers,high loss (sex variable is with 99% of missing value )
df.drop(['id', 'applicant_account_No.', 'bank_sort_code', 'sex', 'credit_application_acceptance'],
        axis=1, inplace=True)

**Seminar 1 page 14**

In [23]:
#printing variable information after dropping unnecesary variables
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58645 entries, 0 to 58644
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       58639 non-null  float64
 1   education_qualifications  58645 non-null  object
 2   income                    58614 non-null  float64
 3   home_ownership            58645 non-null  object
 4   employment_length         58630 non-null  float64
 5   loan_intent               58645 non-null  object
 6   loan_amount               58645 non-null  int64
 7   loan_interest_rate        58635 non-null  float64
 8   loan_income_ratio         58645 non-null  float64
 9   payment_default_on_file   58640 non-null  object
 10  credit_history_length     58645 non-null  int64
 11  loan_approval_status      58644 non-null  object
 12  max_loan_amount(allowed)  58645 non-null  int64
dtypes: float64(5), int64(3), object(5)
memory usage: 5.8+ MB

In [24]:
#checking the remaining columns after removal
df.head()

,age,education_qualifications,income,home_ownership,employment_length,loan_intent,loan_amount,loan_interest_rate,loan_income_ratio,payment_default_on_file,credit_history_length,loan_approval_status,max_loan_amount(allowed)
0,21.0,Unknown,12000.0,OWN,0.0,EDUCATION,15000,6.99,0.12,N,4,Approved,-2426900
1,21.0,Unknown,13200.0,OWN,2.0,EDUCATION,25000,16.77,0.19,Y,3,Approved,-111739
2,23.0,Unknown,9600.0,RENT,5.0,MEDICAL,30000,12.42,0.31,N,3,Approved,-89000
3,40.0,Unknown,182004.0,RENT,3.0,EDUCATION,35000,8.00,0.19,N,11,Approved,35000
4,40.0,Unknown,90000.0,MORTGAGE,3.0,HOMEIMPROVEMENT,35000,12.42,0.39,N,14,Approved,35000

Printing descriptive statistics for the clasification dataset after removing unnessary variables

In [25]:
#printing descriptive statistics for numerical variables
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
age,58639.0,27.555040,6.099005e+00,-30.00,23.00,26.00,30.00,1.800000e+02
income,58614.0,64052.949330,3.793834e+04,4200.00,42000.00,58000.00,75662.00,1.900000e+06
employment_length,58630.0,4.702746,3.999875e+00,0.00,2.00,4.00,7.00,1.500000e+02
loan_amount,58645.0,9217.556518,5.563807e+03,500.00,5000.00,8000.00,12000.00,3.500000e+04
loan_interest_rate,58635.0,10.689216,3.257150e+00,-11.14,7.88,10.75,12.99,2.000000e+02
loan_income_ratio,58645.0,0.159238,9.169179e-02,0.00,0.09,0.14,0.21,8.300000e-01
credit_history_length,58645.0,5.813062,4.027495e+00,2.00,3.00,4.00,8.00,3.000000e+01
max_loan_amount(allowed),58645.0,282353.842715,5.148478e+07,-2426900.00,38003.00,62392.00,92716.00,1.246799e+10

In [26]:
#printing descriptive statistics for categorical variables
df.describe(include='object')

,education_qualifications,home_ownership,loan_intent,payment_default_on_file,loan_approval_status
count,58645,58645,58645,58640,58644
unique,6,4,6,4,8
top,Unknown,RENT,EDUCATION,N,Approved
freq,58303,30594,12271,49933,50210

# Standarize inconsistent categorical labels
**Seminar 2 page 5**

Using map() for srandarize inconsistent labels in loan approval status, Edcuation qualication and payment default on file. Mapping all varints in. to a one single consistent label per category

In [27]:
#standarizing all the label of loan approval status into a single label
df['loan_approval_status'] = df['loan_approval_status'].map({
      'Approved': 'Approved',
      'APPROVED': 'Approved',
      'APPROVED ': 'Approved',
      'Accept': 'Approved',
      'Accept ': 'Approved',
      'Declined': 'Declined',
      'Declined ': 'Declined',
      'DECLINED ': 'Declined',
      'Reject': 'Declined'
 })
df['loan_approval_status'].unique()

array(['Approved', 'Declined', nan], dtype=object)

In [28]:
#standarizing all the labels of education qualification into a single label
df['education_qualifications'] = df['education_qualifications'].map({
      'Unknown': 'Unknown',
      'Unknown ': 'Unknown',
      'Higher Education': 'Higher Education',
      'College': 'College',
      'High School': 'High School',
      'Apprenticeship': 'Apprenticeship',
      'Apprenticeship ': 'Apprenticeship'
  })
df['education_qualifications'].unique()

array(['Unknown', 'Higher Education', 'College', 'High School',
       'Apprenticeship'], dtype=object)

In [29]:
#standarizing all the labels of payment default on file into a single label
df['payment_default_on_file'] = df['payment_default_on_file'].map({
      'N': 'N',
      'NO': 'N',
      'Y': 'Y',
      'YES': 'Y'
})
df['payment_default_on_file'].unique()

array(['N', 'Y', nan], dtype=object)

**seminar 1 page 15**

Rechecking missing value variable after standarization

In [30]:
#checking missing value percentage  after standarization
df.isna().sum() / len(df) *100

age                         0.010231
education_qualifications    0.000000
income                      0.052860
home_ownership              0.000000
employment_length           0.025578
loan_intent                 0.000000
loan_amount                 0.000000
loan_interest_rate          0.017052
loan_income_ratio           0.000000
payment_default_on_file     0.008526
credit_history_length       0.000000
loan_approval_status        0.001705
max_loan_amount(allowed)    0.000000
dtype: float64

# Dropping the rows with missing target values
**seminar 2 page 11**

df.dropna(subset=['loan_approval_status']) for remove rows where the target variable is missing

In [31]:
#dropping the rows where the target variable "loan approval status is missing
df_complete = df.dropna(subset=['loan_approval_status'])

#checking the missing value percentage after dropping the rows which are without the target variable
print(df_complete.isna().sum() / len(df_complete) * 100)

#checking the datashape after dropping the rows with missing target values
print( df_complete.shape)

age                         0.010231
education_qualifications    0.000000
income                      0.052861
home_ownership              0.000000
employment_length           0.025578
loan_intent                 0.000000
loan_amount                 0.000000
loan_interest_rate          0.017052
loan_income_ratio           0.000000
payment_default_on_file     0.008526
credit_history_length       0.000000
loan_approval_status        0.000000
max_loan_amount(allowed)    0.000000
dtype: float64
(58644, 13)

# Numeric variable mean imputation / mode imputation
**seminar 2  page 12**

Mean imputation calculating rhe mean for each numeric variable with missing values and uses fillna() for replacing missing values with the use of column mean. More over Mode imputation is applying to the payment default on file

In [32]:
# using the missing value finding the mean
Mean_Age = df_complete['age'].mean()
Mean_Income = df_complete['income'].mean()
Mean_Employment_Length = df_complete['employment_length'].mean()
Mean_Loan_Interest_Rate = df_complete['loan_interest_rate'].mean()

# filling the misssing value with the mean of age
df_complete['age'].fillna(Mean_Age, inplace=True)

# filling the misssing value with the mean of income
df_complete['income'].fillna(Mean_Income, inplace=True)

# filling the misssing value with the mean of employment length
df_complete['employment_length'].fillna(Mean_Employment_Length, inplace=True)

# filling the misssing value with the mean of loan intrest rate
df_complete['loan_interest_rate'].fillna(Mean_Loan_Interest_Rate, inplace=True)

# filling the misssing value with the mode of payment default on file
Mode_Payment_Default = df_complete['payment_default_on_file'].mode()[0]
df_complete['payment_default_on_file'].fillna(Mode_Payment_Default, inplace=True)

/tmp/ipykernel_64532/1547697984.py:8: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipykernel_64532/1547697984.py:8: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipykernel_64532/1547697984.py:11: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipykernel_64532/1547697984.py:11: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipykernel_64532/1547697984.py:14: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipykernel_64532/1547697984.py:14: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipykernel_64532/1547697984.py:17: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipykernel_64532/1547697984.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/tmp/ipykernel_64532/1547697984.py:21: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipykernel_64532/1547697984.py:21: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

**Seminar 1 page 15**

In [33]:
#verifying that all the missing values are handled after mean imputation
df_complete.isna().sum() / len(data_frame) * 100

age                         0.0
education_qualifications    0.0
income                      0.0
home_ownership              0.0
employment_length           0.0
loan_intent                 0.0
loan_amount                 0.0
loan_interest_rate          0.0
loan_income_ratio           0.0
payment_default_on_file     0.0
credit_history_length       0.0
loan_approval_status        0.0
max_loan_amount(allowed)    0.0
dtype: float64

# Outlier detection

**seminar 2 page 10**

Defining a reusable python funtion which uses the quantile method to identify values which falling bellow q1- 1.5 IQR or above Q3+1.5x IQR as outliers

In [34]:
#IQR funtion for finding outliers
def find_outliers_IQR(df):
      q1 = df.quantile(0.25)
      q3 = df.quantile(0.75)
      IQR = q3 - q1
      outliers = df[((df < (q1 - 1.5 * IQR)) | (df > (q3 + 1.5 * IQR)))]
      return outliers

Filtering out imposible ages values which are bellow 18 and over 100 using logical operators for removing the recording errors

In [35]:
#checking the age before filtering
print("Age min:", df['age'].min())
print("Age max:", df['age'].max())

Age min: -30.0
Age max: 180.0

**Seminar 1 page 19**

In [36]:
#filtetring imposible age values
df_complete = df_complete[df_complete['age'] >= 18]
df_complete = df_complete[df_complete['age'] <= 100]

#checking age range aftr filtering
print("Age min:", df_complete['age'].min())
print("Age max:", df_complete['age'].max())

Age min: 20.0
Age max: 84.0

**Seminar 1 page 19**

Applies the IQR funtion for detect and remove outliers in income, loan amount and max loan amount using dropna()

In [37]:
#using IQR funtion for finding and remove outliers in income

print("dataframesize before removal",df_complete.shape)
income_outliers = find_outliers_IQR(df_complete['income'])
print("income outliers:", len(income_outliers))
df_complete.drop(income_outliers.index, inplace=True)
print("dataframesize after removal",df_complete.shape)

dataframesize before removal (58638, 13)
income outliers: 2411
dataframesize after removal (56227, 13)

In [38]:
#using IQR funtion for finding and remove outliers in loan amount
print("dataframesize before removal",df_complete.shape)
loan_outliers = find_outliers_IQR(df_complete['loan_amount'])
print("loan_amount outliers:", len(loan_outliers))
df_complete.drop(loan_outliers.index, inplace=True)
print("dataframesize after removal",df_complete.shape)

dataframesize before removal (56227, 13)
loan_amount outliers: 1542
dataframesize after removal (54685, 13)

In [39]:
#using IQR funtion for finding and remove outliers in max loan amount
print("dataframesize before removal",df_complete.shape)
max_loan_outliers = find_outliers_IQR(df_complete['max_loan_amount(allowed)'])
print(" max_loan_amount outliers:", len(max_loan_outliers))
df_complete.drop(max_loan_outliers.index, inplace=True)
print("dataframesize after removal",df_complete.shape)

dataframesize before removal (54685, 13)
 max_loan_amount outliers: 1080
dataframesize after removal (53605, 13)

PLotting interactive chart for the loan approval status

In [40]:
#plotting the loan approval status
approval_fig = px.histogram(df_complete, x='loan_approval_status',
                             title='Distribution of Loan Approval Status (0=Approved, 1=Declined)')
approval_fig.show()

# Encoding categorical variables
**Seminar 1 page 18**

encoding the categorical variables with the useof LabelEncoder(). this automatically encode all categorical variables into numeric labels

In [41]:
#creating a label encoder instance
label_encoder = preprocessing.LabelEncoder()
#encoding education qualifications
df_complete['education_qualifications'] = label_encoder.fit_transform(df_complete['education_qualifications'])
#encoding home ownership
df_complete['home_ownership'] = label_encoder.fit_transform(df_complete['home_ownership'])
#encoding loan intent
df_complete['loan_intent'] = label_encoder.fit_transform(df_complete['loan_intent'])
#encoding payment default on file
df_complete['payment_default_on_file'] = label_encoder.fit_transform(df_complete['payment_default_on_file'])
#encoding loan approval status
df_complete['loan_approval_status'] = label_encoder.fit_transform(df_complete['loan_approval_status'])
#checking the rows after encoding

df_complete.head()

,age,education_qualifications,income,home_ownership,employment_length,loan_intent,loan_amount,loan_interest_rate,loan_income_ratio,payment_default_on_file,credit_history_length,loan_approval_status,max_loan_amount(allowed)
20,40.0,4,125000.0,0,1.0,4,21000,6.99,0.17,0,16,0,21000
21,40.0,4,120000.0,2,4.0,0,20000,15.95,0.17,0,15,0,20000
22,40.0,4,60000.0,0,13.0,2,20000,14.54,0.33,0,14,0,20000
23,40.0,4,80000.0,2,10.0,4,20000,18.62,0.25,0,14,0,20000
24,40.0,4,72000.0,3,3.0,2,20000,13.47,0.28,0,16,0,20000

**Seminar 1 page 14**

In [42]:
#checking that all the data types are numeric after encoding
df_complete.info()

<class 'pandas.core.frame.DataFrame'>
Index: 53605 entries, 20 to 55640
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       53605 non-null  float64
 1   education_qualifications  53605 non-null  int64
 2   income                    53605 non-null  float64
 3   home_ownership            53605 non-null  int64
 4   employment_length         53605 non-null  float64
 5   loan_intent               53605 non-null  int64
 6   loan_amount               53605 non-null  int64
 7   loan_interest_rate        53605 non-null  float64
 8   loan_income_ratio         53605 non-null  float64
 9   payment_default_on_file   53605 non-null  int64
 10  credit_history_length     53605 non-null  int64
 11  loan_approval_status      53605 non-null  int64
 12  max_loan_amount(allowed)  53605 non-null  int64
dtypes: float64(5), int64(8)
memory usage: 5.7 MB

# Creating 2 datasets

Creating the clasification dataset for the clasification part by dropping the max loan amount column from the cleaned dataset using drop()

In [43]:
#creating clasification dataset for predicting the loan approval status
#removing max loan amount as it is the regression target
df_classification = df_complete.drop(['max_loan_amount(allowed)'], axis=1)
#printing the clasification dataset shape
print('clasification dataset shape:', df_classification.shape)
#printing the first 5 rows
df_classification.head()

clasification dataset shape: (53605, 12)

,age,education_qualifications,income,home_ownership,employment_length,loan_intent,loan_amount,loan_interest_rate,loan_income_ratio,payment_default_on_file,credit_history_length,loan_approval_status
20,40.0,4,125000.0,0,1.0,4,21000,6.99,0.17,0,16,0
21,40.0,4,120000.0,2,4.0,0,20000,15.95,0.17,0,15,0
22,40.0,4,60000.0,0,13.0,2,20000,14.54,0.33,0,14,0
23,40.0,4,80000.0,2,10.0,4,20000,18.62,0.25,0,14,0
24,40.0,4,72000.0,3,3.0,2,20000,13.47,0.28,0,16,0

Creating the regression dataset by filtering only the approved applicant using a logical filter and dropping out the loan approval status column

In [45]:
#filtering out the approved applicant for the regression dataset
df_regression = df_complete[df_complete['loan_approval_status'] == 0]

#removing out loan approval target as it is the clasificatio. target
df_regression = df_regression.drop(['loan_approval_status'], axis=1)

#dropping any regression missing value from the regression dataset
df_regression = df_regression.dropna()

#printing out thr missing values
print('missing values :', df_regression.isnull().sum().sum())
#printing the shape

print('regresion dataset shape:', df_regression.shape)
#printing the first 5 rows
df_regression.head()

missing values : 0
regresion dataset shape: (45910, 12)

,age,education_qualifications,income,home_ownership,employment_length,loan_intent,loan_amount,loan_interest_rate,loan_income_ratio,payment_default_on_file,credit_history_length,max_loan_amount(allowed)
20,40.0,4,125000.0,0,1.0,4,21000,6.99,0.17,0,16,21000
21,40.0,4,120000.0,2,4.0,0,20000,15.95,0.17,0,15,20000
22,40.0,4,60000.0,0,13.0,2,20000,14.54,0.33,0,14,20000
23,40.0,4,80000.0,2,10.0,4,20000,18.62,0.25,0,14,20000
24,40.0,4,72000.0,3,3.0,2,20000,13.47,0.28,0,16,20000

# Saving dataset
**Seminar 1 page 23**

save both clasification and regression datasets in CSV formt files using to_csv()

In [46]:
#saving clasification dataset
df_classification.to_csv(r'/content/Prepared_Classification_Dataset.csv', index=False)

In [47]:
#saving regression dataset
df_regression.to_csv(r'/content/Prepared_Regression_Dataset.csv', index=False)